# version: '3.8'

# services:
#   api:
#     build: .
#     volumes:
#       - .:/app
#     ports:
#       - "8000:8000"


version: "3.9"
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000
