services:
  - type: web
    name: api
    env: docker
    dockerfilePath: ./Dockerfile

  - type: worker
    name: celery
    env: docker
    dockerfilePath: ./Dockerfile

  - type: redis
    name: redis
    ipAllowList:
      - "0.0.0.0/0"  # Adjust this for production
