services:
  - type: web
    name: api-service
    region: singapore
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    numInstances: 1
    healthCheckPath: /healthz
    envVars:
      - key: REDIS_URL
        fromService:
          name: redis
          property: host
    ports:
      - port: 8000
        protocol: http
    dependsOn:
      - redis

  - type: worker
    name: celery-worker
    region: singapore
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    numInstances: 1
    startCommand: celery -A celery_app worker --loglevel=info
    dependsOn:
      - redis
    envVars:
      - key: REDIS_URL
        fromService:
          name: redis
          property: host

  - type: redis
    name: redis
    region: singapore
    plan: free
    image: redis:alpine

databases:
  - name: bytebase-metadb
    region: singapore
    plan: free
    postgresMajorVersion: 15
